config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get 'profile/app_page', to: 'profiles#app_page', as: 'app_layout_page'
  get 'trainings/suggestions', to: 'trainings#suggestions', as: 'training_suggestions'
  get 'boards/bookmarks', to: 'bookmarks#index', as: 'bookmarks_boards'
  get 'bgm', to: 'bgms#index', as: 'bgm_selection'
  get 'gyms', to: 'gyms#index', as: 'gyms'
  # config/routes.rb
  get 'ai/generate_training_plan', to: 'ai#generate_training_plan'
  get 'training_suggestions', to: 'trainings#suggestions'
  post 'training_suggestions', to: 'trainings#generate_training_plan'
  get 'gemini_training_suggestions', to: 'trainings#gemini_suggestions'
  get 'trainings/new_training_suggestion', to: 'trainings#new_training_suggestion'
  post 'trainings', to: 'trainings#create_training_suggestion'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, shallow: true, only: %i[create edit update destroy]
    resource :bookmark, only: [:create, :destroy]
  end  
  resource :profile, only: [:show, :edit, :update]
  resources :password_resets, only: %i[new create edit update]
  
  namespace :admin do
    root "dashboards#index"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :boards
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy', as: :logout
  end
  resources :trainings, only: [:index, :new, :create, :edit, :update, :destroy, :show]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to t('header.login'), login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">エラーがあります:</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, message| %>
   <div class="alert alert-<%= key %>">
    <%= message %>
   </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'screenshot_2024_09_13_113931.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        

        

        <li class='nav-item'>
          <%= link_to "マイページ", app_layout_page_path, class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <%= image_tag 'sample.jpg', class: 'rounded-circle mr15', width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'><%= current_user.decorate.full_name %></div>
            <div class='dropdown-divider'></div>
            <% if logged_in? && current_user.avatar? %>
  <%= link_to profile_path, class: 'dropdown-item' do %>
    <%= image_tag current_user.avatar.url, alt: t('header.profile'), class: 'avatar-image' %>
    <%= t('header.profile') %>
  <% end %>
<% else %>
  <%= link_to t('header.profile'), profile_path, class: 'dropdown-item' %>
<% end %>

            <%= link_to t('header.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>