config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root "static_pages#top"
  get 'profile/app_page', to: 'profiles#app_page', as: 'app_layout_page'
  get 'trainings/suggestions', to: 'trainings#suggestions', as: 'training_suggestions'
  get 'boards/bookmarks', to: 'bookmarks#index', as: 'bookmarks_boards'
  get 'bgm', to: 'bgms#index', as: 'bgm_selection'
  get 'gyms', to: 'gyms#index', as: 'gyms'
  # config/routes.rb
  get 'ai/generate_training_plan', to: 'ai#generate_training_plan'
  get 'training_suggestions', to: 'trainings#suggestions'
  post 'training_suggestions', to: 'trainings#generate_training_plan'
  get 'gemini_training_suggestions', to: 'trainings#gemini_suggestions'
  get 'trainings/new_training_suggestion', to: 'trainings#new_training_suggestion'
  post 'trainings', to: 'trainings#create_training_suggestion'
  resources :users, only: %i[new create]
  resources :boards do
    resources :comments, shallow: true, only: %i[create edit update destroy]
    resource :bookmark, only: [:create, :destroy]
  end  
  resource :profile, only: [:show, :edit, :update]
  resources :password_resets, only: %i[new create edit update]
  
  namespace :admin do
    root "dashboards#index"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :boards
    get 'login', to: 'user_sessions#new', as: :login
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy', as: :logout
  end
  resources :trainings, only: [:index, :new, :create, :edit, :update, :destroy, :show]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
  mount_uploader :board_image, ImageUploader

  belongs_to :user
  validate :board_image_type
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :board_image
  has_many :bookmarking_users, through: :bookmarks, source: :user

  private

  def board_image_type
    allowed_formats = %w[jpg jpeg png gif]
    return unless board_image.present? && !board_image.content_type.in?(allowed_formats.map { |format| "image/#{format}" })

    errors.add(:board_image, 'must be a JPEG, PNG, or GIF')
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::BaseController
  before_action :set_board, only: %i[edit update show destroy]

  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @board.update(board_params)
      redirect_to admin_board_path(@board), success: t('defaults.flash_message.updated2', item: Board.model_name.human)
    else
      flash.now['danger'] = t('defaults.flash_message.not_updated', item: Board.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @board.destroy!
    redirect_to admin_boards_path, success: t('defaults.flash_message.deleted', item: Board.model_name.human), status: :see_other
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[edit update destroy]
  before_action :set_board_for_show, only: %i[show]

  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result.includes(:user).page(params[:page])
  end

  def show
    @user = @board.user
    render :show, locals: { board: @board }
  end

  def new
    @board = Board.new
  end

  def edit
    # 既に @board を取得しているため、何もしない
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, success: t('defaults.flash_message.created', item: Board.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_created', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @board.update(board_params)
      flash[:success] = t('flash.success.board_updated')
      redirect_to @board
    else
      flash.now[:danger] = t('flash.alert.board_not_updated')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_url, success: '掲示板を削除しました', status: :see_other
  end

  def bookmarks
    @q = Board.joins(:bookmarks).where(bookmarks: { user_id: current_user.id }).ransack(params[:q])
    @bookmarked_boards = @q.result(distinct: true).includes(:user).page(params[:page])
  end

  private

  def set_board
    @board = Board.find_by(id: params[:id], user_id: current_user.id)
    raise ActiveRecord::RecordNotFound unless @board
  end

  def set_board_for_show
    @board = Board.find(params[:id])
    return if @board.present? && (@board.user == current_user || !current_user.boards.exists?(id: @board.id))

    redirect_to boards_path, alert: t('flash.alert.not_found')
  end

  def board_params
    params.require(:board).permit(:title, :body, :board_image)
  end
end

app/views/admin/boards/_board.html.erb
<tr>
  <td>
    <%= board.id %>
  </td>
  <td>
    <%= board.title %>
  </td>
  <td>
    <%= board.user.decorate.full_name %>
  </td>
  <td>
    <%= l board.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_board_path(board), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_board_path(board), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_board_path(board), data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/boards/_search_form.html.erb
<%= search_form_for @q, url: admin_boards_path do |f| %>
    <div class="row">
      <div class="d-flex align-items-center justify-content-center">
        <div class="d-inline me-3">
          <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
        </div>
        <div class="d-flex me-3">
          <%= f.date_field :created_at_gteq, class: 'form-control' %>
          <span class="mx-1">〜</span>
          <%= f.date_field :created_at_lteq_end_of_day, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

app/views/admin/boards/edit.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('boards.edit.title') %></h1>
      <%= form_with model: @board, url: admin_board_path(@board), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 10 %>
        </div>
        <div class="form-group">
          <%= f.label :board_image %>
          <%= f.file_field :board_image, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
          <%= f.hidden_field :board_image_cache %>
        </div>
        <div class='mt-3 mb-3'>
          
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Board.human_attribute_name(:id) %></th>
          <th scope="col"><%= Board.human_attribute_name(:title) %></th>
          <th scope="col"><%= Board.human_attribute_name(:user) %></th>
          <th scope="col"><%= Board.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @boards %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @boards, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/admin/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h1><%= t('boards.show.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_board_path(@board), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_board_path(@board), data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:id) %></th>
          <td><%= @board.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:title) %></th>
          <td><%= @board.title %></td>
        </tr>
        <tr>
        <th scope="row"><%= Board.human_attribute_name(:body) %></th>
          <td><%= @board.body %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:user_id) %></th>
          <td><%= @board.user.decorate.full_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:created_at) %></th>
          <td><%= l @board.created_at, format: :long %></td>
        </tr>
        
      </table>
    </div>
  </div>
</div>